algoritmo  "exercicio 1 - Programação e algoritmos"

var

A, B, C, D: inteiro

inicio

escreva("Soma de 3 valores!")
escreval("")

escreva("Entre o 1º valor inteiro: ")
leia(A)
escreva("Entre o 2º valor inteiro: ")
leia(B)
escreva("Entre o 3º valor inteiro: ")
leia(C)

D <- A + B + C
se D >= 100 entao
   escreval(D)
senao
   escreva("Só iremos exibir o resultado da soma se ela for maior que 100")
fimse

fimalgoritmo
